### ISSUE TITLE
Subtitles ??

### ISSUE THREAD

**Issue by ryouki-des** [BurningSands70/stremio-downloader#12]
I always watch animes in japanese so maybe a way to download the subtitles aswell

**Comment by BurningSands70** [comment]
This is not needed, the app has an addon available (press "Options" to see the install button), everything you download becomes available through the Stremio addon, so if Stremio found subtitles for that video before downloading, it should continue to find the subtitles for the downloaded one too when using the addon.

**Comment by sleeyax** [comment]
> 
> 
> This is not needed, the app has an addon available (press "Options" to see the install button), everything you download becomes available through the Stremio addon, so if Stremio found subtitles for that video before downloading, it should continue to find the subtitles for the downloaded one too when using the addon.

I think he's downloading the videos for use without the Stremio app @BurningSands70 ...
Imo out of scope for this project, but just commenting it here to speed things up.

**Comment by ryouki-des** [comment]
> > This is not needed, the app has an addon available (press "Options" to see the install button), everything you download becomes available through the Stremio addon, so if Stremio found subtitles for that video before downloading, it should continue to find the subtitles for the downloaded one too when using the addon.
> 
> I think he's downloading the videos for use without the Stremio app @BurningSands70 ...
> Imo out of scope for this project, but just commenting it here to speed things up.

wait remind me again, how do i watch in the app ? lol

**Comment by BurningSands70** [comment]
@ryouki-des In the Downloader app, press "Options" in the upper right corner, and there is a "Install Downloader as Add-on" button there, press that.

**Comment by BurningSands70** [comment]
Closing this as I also think it is out of scope for the project..
