### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by Nishant765** [BurningSands70/stremio-downloader#13]
While downloading some episodes, the downloader gives an error saying that A JavaScript error occurred in the main process. The episode downloads as usual but gets stuck at 100% and don't get finished. Any solution for this?

**Comment by BurningSands70** [comment]
Are you on Windows? I think this is the same issue as this one: https://github.com/BurningSands70/stremio-downloader/issues/10

I'll try to make a new release with the fix as soon as possible.

**Comment by Nishant765** [comment]
Yes I am on windows. Apparently I found out the cause of the issue. In windows file names cannot have special characters like ? ' and so on. As the downloader downloads the files with the same name as that of the episode/movie name it's causing this error.

**Comment by BurningSands70** [comment]
Yes, I know, this is the same issue as https://github.com/BurningSands70/stremio-downloader/issues/10 as I said, the code already includes a fix, I just need to make a new release, I will do it as soon as possible..

**Comment by Nishant765** [comment]
Yes that's fine! Take your time. It's not a major issue. And thank you for this amazing downloader.

**Comment by BurningSands70** [comment]
I've just released v1.0.5 that should fix this bug:
https://github.com/BurningSands70/stremio-downloader/releases/tag/v1.0.5

Please test it and reopen this issue if the problem persists.
