### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by lgdelai** [BurningSands70/stremio-downloader#14]
I searched on windows and found no uninstall button.

**Comment by BurningSands70** [comment]
Simply delete it's folder (the one you extracted from the archive) and in order to also delete the user data related to it, delete this folder:
`%AppData%\stremio-downloader`

That's it..

**Comment by lgdelai** [comment]
Hello.
Thanks for the feedback.

I exclude only the folder used to install the addon.
the one I unzipped and ran to do the installation.

When I right click on the Stremio screen, it still displays the download options.

I have to delete the% AppData% \ stremio-downloader folder
  so that he is permanently excluded from the stremium?
or is there anything else i should do?

Thank you.

**Comment by BurningSands70** [comment]
You are confusing things, if you removed the unpacked archive folder, and if you also removed the folder from `%AppData%\stremio-downloader`, then this application is completely removed from your system.

This application, when installed, is used [as described in the readme](https://github.com/BurningSands70/stremio-downloader/blob/master/README.md), the right click option from Stremio that gives the download options has nothing to do with the Stremio Downloader application, that is a new feature from the Stremio app.
