### ISSUE TITLE
How to View downloads - mac

### ISSUE THREAD

**Issue by melkerll** [BurningSands70/stremio-downloader#18]
Hi, im struggling to actually view the downloads on my macbook. The shows come up in your downloader but as .mkv, and im not sure what to use as a viewer. Please help.
Thanks, Melker

**Comment by boerredus** [comment]
`mkv` is a video file extension. In order to open `mkv` files, you can use basically any media player. I guess that Mac has a video player built-in that is able to play `mkv` files. Anyway, you can try using VLC media player.

**Comment by boerredus** [comment]
In fact, I'm pretty sure that even the Stremio application itself can play it.

**Comment by BurningSands70** [comment]
@TheMelker as @bored-user  said, any video player (VLC, MPV, etc.) will play it. Or you can install the Stremio addon that this app provides to play the content in Stremio directly, it will show all downloads in a different catalog, with movie data / episode list, etc.
