### ISSUE TITLE
how/where to install

### ISSUE THREAD

**Issue by TheLumineer** [BurningSands70/stremio-downloader#19]
Hiya pal, trying to get this up and running but dont know where to start. i have the zip file downloaded, where to extract/install it?

**Comment by sleeyax** [comment]
Doesn't matter where you extract it, just extract it somewhere e.g in you Downloads or Documents folder.

**Comment by TheLumineer** [comment]
cheers pal, think i was overthinking it!

Will give it a go now. One last thing, does this replace the ability to
stream in the app, or add the choice to stream AND  download to local
device?

**Comment by sleeyax** [comment]
Why don't you try it out and see for yourself? This app is non-destructive to your Stremio installation and you can always remove it if it's not what you're looking for ¯\_(ツ)_/¯

**Comment by BurningSands70** [comment]
@TheLumineer It doesn't stop Stremio from being able to stream, it runs a separate Stremio instance in the browser that gives the ability to download content (instead of streaming it).
